/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

/**
 *
 * @author Le chiffre
 */
public class acuill extends javax.swing.JFrame {

    /**
     * Creates new form acuill
     */
    public acuill() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonSatistique = new javax.swing.JButton();
        ButtonAdmin = new javax.swing.JButton();
        buttonClient = new javax.swing.JButton();
        ButtonPrestateur = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(233, 213, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12), new java.awt.Color(135, 8, 165))); // NOI18N
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        ButtonSatistique.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/125px-Nuvola_apps_kchart.png"))); // NOI18N
        ButtonSatistique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSatistiqueActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSatistique);
        ButtonSatistique.setBounds(440, 80, 83, 59);

        ButtonAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/droits-administrateur-facebook.png"))); // NOI18N
        ButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAdminActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAdmin);
        ButtonAdmin.setBounds(450, 240, 83, 59);

        buttonClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Client-2-icon_1.png"))); // NOI18N
        buttonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientActionPerformed(evt);
            }
        });
        jPanel1.add(buttonClient);
        buttonClient.setBounds(70, 80, 80, 60);

        ButtonPrestateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2011-07-23-23-forrester-logo.jpg"))); // NOI18N
        ButtonPrestateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPrestateurActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPrestateur);
        ButtonPrestateur.setBounds(70, 250, 83, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/just_married_by_meago-d4v6nvr.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 80, 310, 270);

        jLabel2.setText("Client");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 150, 60, 14);

        jLabel3.setText("Prestateur");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 320, 60, 14);

        jLabel4.setText("Administration");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(450, 310, 80, 14);

        jLabel5.setText("Statistique");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(450, 150, 70, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSatistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSatistiqueActionPerformed
      
    }//GEN-LAST:event_ButtonSatistiqueActionPerformed

    private void buttonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientActionPerformed
        client buttonClient=new client ();
        buttonClient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonClientActionPerformed

    private void ButtonPrestateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPrestateurActionPerformed
         Presttaire ButtonPrestateur=new Presttaire ();
        ButtonPrestateur.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonPrestateurActionPerformed

    private void ButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAdminActionPerformed
         newadmine ButtonAdmin=new newadmine ();
        ButtonAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acuill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acuill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acuill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acuill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acuill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAdmin;
    private javax.swing.JButton ButtonPrestateur;
    private javax.swing.JButton ButtonSatistique;
    private javax.swing.JButton buttonClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
