package GoldenCage.gui;

import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserAdapter;
import chrriis.dj.nativeswing.swtimpl.components.WebBrowserNavigationEvent;
import GoldenCage.Dao.ComptesDAO;
import GoldenCage.entites.Comptes;
import facebookconnect.FacebookTestClient;
import facebookconnect.GraphReaderExample;
import static facebookconnect.Main.access_token;
import static facebookconnect.Main.firstRequest;
import static facebookconnect.Main.firstRequestDone;
import static facebookconnect.Main.secondRequest;
import static facebookconnect.Main.secondRequestDone;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.StringReader;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.parser.ParserDelegator;




/**
 *
 * @author FGH
 */
public class fr_connexion extends javax.swing.JFrame {

    /**
     * Creates new form fr_connexion
     */
    public fr_connexion() {
        ComptesDAO comptesDAO= new ComptesDAO();
        List<Comptes> comptes = comptesDAO.afficherComptes();
        if(comptes.size()==0){
            insecrition_client_presat ins = new insecrition_client_presat(-1);
            ins.setVisible(true);
            this.dispose();
        }else{
        initComponents();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alert_quit = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        lb_mdp = new javax.swing.JLabel();
        lb_login = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        lb_photogoldencage = new javax.swing.JLabel();
        bt_connecter = new javax.swing.JButton();
        bt_quitter = new javax.swing.JButton();
        lb_glodencage = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        alert = new javax.swing.JLabel();
        pf_pwd = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Golden Cage");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(233, 213, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connexion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(135, 8, 165))); // NOI18N
        jPanel1.setLayout(null);

        lb_mdp.setFont(new java.awt.Font("Aharoni", 3, 18)); // NOI18N
        lb_mdp.setForeground(new java.awt.Color(255, 255, 255));
        lb_mdp.setText("Mot de passe :");
        jPanel1.add(lb_mdp);
        lb_mdp.setBounds(260, 220, 140, 30);

        lb_login.setFont(new java.awt.Font("Aharoni", 3, 18)); // NOI18N
        lb_login.setForeground(new java.awt.Color(255, 255, 255));
        lb_login.setText("Login :");
        jPanel1.add(lb_login);
        lb_login.setBounds(260, 170, 140, 30);
        jPanel1.add(txt_login);
        txt_login.setBounds(400, 170, 240, 30);
        jPanel1.add(lb_photogoldencage);
        lb_photogoldencage.setBounds(10, 20, 260, 240);

        bt_connecter.setBackground(new java.awt.Color(255, 153, 255));
        bt_connecter.setText("Se connecter");
        bt_connecter.setPreferredSize(new java.awt.Dimension(209, 39));
        bt_connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_connecterActionPerformed(evt);
            }
        });
        jPanel1.add(bt_connecter);
        bt_connecter.setBounds(270, 320, 110, 30);

        bt_quitter.setBackground(new java.awt.Color(255, 153, 255));
        bt_quitter.setText("Quitter");
        bt_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quitterActionPerformed(evt);
            }
        });
        jPanel1.add(bt_quitter);
        bt_quitter.setBounds(420, 320, 110, 30);
        jPanel1.add(lb_glodencage);
        lb_glodencage.setBounds(280, 40, 260, 80);

        jButton2.setText("s'inscrire");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 360, 110, 30);
        jPanel1.add(alert);
        alert.setBounds(310, 270, 210, 30);
        jPanel1.add(pf_pwd);
        pf_pwd.setBounds(400, 220, 240, 30);

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(70, 320, 170, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(672, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_connecterActionPerformed
       
 String pseudo=txt_login.getText();
        String motDePasse=pf_pwd.getText();
         ComptesDAO  ComptesDAO= new ComptesDAO ();
            Comptes compt =  ComptesDAO.Authentification(pseudo, motDePasse); 
            if(compt!=null){
                 // fr_acceuil adfminMenu=new fr_acceuil(compt.getIdCompte());
                  //adminMenu.setVisible(true);
                 
                 //this.dispose();
                if(compt.getTypeCompte().equals("client")) {
                    System.out.println("client");// just declare les interface c pret
                }
                else if(compt.getTypeCompte().equals("ADMIN")){
                    System.out.println("ADMIN");// just declare les interface c pret
                }
                else if (compt.getTypeCompte().equals("prestatair")){
                     System.out.println("prestatair");// just declare les interface c pret
                }
                else if (compt.getTypeCompte().equals("SuperAdmin")){
                Super_admin ll=new  Super_admin();
                 ll.setVisible(true);
                  dispose();
                    
                }
            }
            else{
                alert.setText("verifier votre psudeo et mot de pass SVP");
                
            }
    }//GEN-LAST:event_bt_connecterActionPerformed

    private void bt_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quitterActionPerformed
      this.dispose();
    }//GEN-LAST:event_bt_quitterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         insecrition_client_presat go_insecri= new insecrition_client_presat();
        go_insecri.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {

                NativeInterface.open();
                NativeInterface.initialize();
                FacebookTestClient testClient = new FacebookTestClient();

                
                
                testClient.setgetPermissionsForAppListener(new ActionListener() {

  @Override
  public void actionPerformed(ActionEvent e) {
    final JFrame authFrame = new JFrame();
    // Create the JWebBrowser and add the WebBrowserAdapter
    JPanel webBrowserPanel = new JPanel(new BorderLayout());
    final JWebBrowser webBrowser = new JWebBrowser();
    webBrowser.navigate(firstRequest);
    webBrowser.addWebBrowserListener(new WebBrowserAdapter() {
      @Override
      public void locationChanged(WebBrowserNavigationEvent e) {
        super.locationChanged(e);
        // Check if first request was not done
        if (!firstRequestDone) {
          // Check if you left the location and were redirected to the next 
          // location
          if (e.getNewResourceLocation().contains("http://www.facebook.com/connect/login_success.html?code=")){
            // If it successfully redirects you, get the verification code
            // and go for a second request
            String[] splits = e.getNewResourceLocation().split("=");
            String stage2temp = secondRequest + splits[1];
              System.out.println("First ="+splits[1]);
            webBrowser.navigate(stage2temp);
            firstRequestDone = true;
          }
        } else {
          // If secondRequest is not done yet, you perform this and get the 
          // access_token
          if (!secondRequestDone) {
            System.out.println(webBrowser.getHTMLContent());
            // Create reader with the html content
            StringReader readerSTR = new StringReader(webBrowser.getHTMLContent());
            // Create a callback for html parser
            HTMLEditorKit.ParserCallback callback = 
            new HTMLEditorKit.ParserCallback() {
                @Override
              public void handleText(char[] data,int pos) {
                System.out.println(data);
                // because there is only one line with the access_token 
                // in the html content you can parse it.
                String string = new String(data);
                String[] temp1 = string.split("&");
                String[] temp2 = temp1[0].split("=");
                    System.out.println("access tocken="+temp2);
                        access_token = temp2[1];
                    GraphReaderExample graphReaderExample= new GraphReaderExample(access_token);
                    graphReaderExample.runEverything();
                    dispose();
                    
                
                
              }
            };
            try {
              // Call the parse method 
              new ParserDelegator().parse(readerSTR,callback,false);
            } catch (IOException e1) {
              e1.printStackTrace();
            }
            // After everything is done, you can dispose the jframe
            authFrame.dispose(); 
            
            
          }
        }
      }
    });
    webBrowserPanel.add(webBrowser,BorderLayout.CENTER);
    authFrame.add(webBrowserPanel);
    authFrame.setSize(400, 500);
    authFrame.setVisible(true);
    
    
    
  
  }
  
});
                
                
      
            }
            
            
         
        });
       
        
      this.dispose();
       
                
 
        
                                           

                                            
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new fr_connexion().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane Alert_quit;
    private javax.swing.JLabel alert;
    private javax.swing.JButton bt_connecter;
    private javax.swing.JButton bt_quitter;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_glodencage;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_mdp;
    private javax.swing.JLabel lb_photogoldencage;
    private javax.swing.JPasswordField pf_pwd;
    private javax.swing.JTextField txt_login;
    // End of variables declaration//GEN-END:variables
}
