/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GoldenCage.gui;

import GoldenCage.Dao.ComptesDAO;
import GoldenCage.entites.Comptes;
import ftpconnection.FTPUploader;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
/**
 *
 * @author FGH
 */
public class insecrition_client_presat extends javax.swing.JFrame {

    int state;
    
     private String imgupload;
   private String hostDir="public_html/userimg/";
   private String imagename;
    
      
    
    /**
     * Creates new form fr_acceuil
     */
    public insecrition_client_presat(int state) {
        initComponents();
        this.state=state;
         build();//On initialise notre fenêtre
         if(state == -1){
             combo_type.setVisible(false);
             lbltype.setText("Registration Super Admin");
         }
    }

    insecrition_client_presat() {
        initComponents();
        
         build();//On initialise notre fenêtre
    }

    
    private void build(){
		setTitle("Ma première fenêtre"); //On donne un titre à l'application
		setSize(1000,650); //On donne une taille à notre fenêtre
		setLocationRelativeTo(null); //On centre la fenêtre sur l'écran
		setResizable(false); //On interdit la redimensionnement de la fenêtre
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //On dit à l'application de se fermer lors du clic sur la croix
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alert_quit = new javax.swing.JOptionPane();
        p_liste = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        combo_type = new javax.swing.JComboBox();
        lbltype = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_pseudo = new javax.swing.JTextField();
        bt_ok = new javax.swing.JButton();
        pf_pwd = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        j_image = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tf_nom = new javax.swing.JTextField();
        tf_prenom = new javax.swing.JTextField();
        tf_adresse = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_tel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        p_liste.setBackground(new java.awt.Color(233, 213, 230));
        p_liste.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12), new java.awt.Color(135, 8, 165))); // NOI18N
        p_liste.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p_liste.setPreferredSize(new java.awt.Dimension(682, 82));
        p_liste.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(244, 191, 242));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Compt Client", "Compt Prestatair" }));
        jPanel1.add(combo_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 150, -1));

        lbltype.setFont(new java.awt.Font("Vivaldi", 3, 24)); // NOI18N
        lbltype.setForeground(new java.awt.Color(84, 149, 238));
        lbltype.setText("Type Compte");
        jPanel1.add(lbltype, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 140, -1));

        jLabel3.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nom:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 71, -1));

        jLabel4.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prenom:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 106, -1));

        jLabel5.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adresse:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 106, -1));

        jLabel6.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-mail:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 106, -1));

        jLabel7.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Num Tel:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 106, -1));

        jLabel8.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pseudo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 106, -1));

        jLabel9.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mot de Passe:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 162, -1));
        jPanel1.add(tf_pseudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 300, -1));

        bt_ok.setText("Registration");
        bt_ok.setPreferredSize(new java.awt.Dimension(129, 33));
        bt_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_okActionPerformed(evt);
            }
        });
        jPanel1.add(bt_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));
        jPanel1.add(pf_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 300, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(129, 120));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        j_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j_image.setText("Photo");
        j_image.setPreferredSize(new java.awt.Dimension(129, 120));
        jPanel2.add(j_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, -1, -1));

        jButton1.setText("parcourire");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 180, 100, -1));
        jPanel1.add(tf_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 300, -1));
        jPanel1.add(tf_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 300, -1));
        jPanel1.add(tf_adresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 300, -1));
        jPanel1.add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 300, -1));
        jPanel1.add(tf_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 300, -1));

        jLabel10.setFont(new java.awt.Font("Wide Latin", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pseudo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 106, -1));

        p_liste.add(jPanel1);
        jPanel1.setBounds(210, 20, 760, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_liste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_liste, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formWindowOpened

    private void bt_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_okActionPerformed
        // TODO add your handling code here:
        Comptes compt =new Comptes();
        compt.setNom(tf_nom.getText());
        compt.setAdresse(tf_adresse.getText());
        compt.setEmail(tf_email.getText());
        compt.setMotDePasse(pf_pwd.getText());
        compt.setPrenom(tf_prenom.getText());
        compt.setNumTel(Integer.parseInt(tf_tel.getText()));
        compt.setPseudo(tf_pseudo.getText());
        if(state==(-1)){
            compt.setTypeCompte("SuperAdmin");
            
        }else {
            if(combo_type.getSelectedIndex()==0){
            compt.setTypeCompte("Client");
        }
        else{
            compt.setTypeCompte("Prestataire");
        }
        }
        compt.setUrlphoto("http://goldencage.comli.com/userimg/"+imagename);
        FTPUploader ftpUploader = null;
       try {
           ftpUploader = new FTPUploader();
       } catch (Exception ex) {
           Logger.getLogger(insecrition_client_presat.class.getName()).log(Level.SEVERE, null, ex);
       }
       try {
           //FTP server path is relative. So if FTP account HOME directory is "/home/pankaj/public_html/" and you need to upload 
           // files to "/home/pankaj/public_html/wp-content/uploads/image2/", you should pass directory parameter as "/wp-content/uploads/image2/"
           System.out.println("111");
           ftpUploader.uploadFile(imgupload, hostDir, "");
           System.out.println("222");
           
       } catch (Exception ex) {
           Logger.getLogger(insecrition_client_presat.class.getName()).log(Level.SEVERE, null, ex);
       }
        ftpUploader.disconnect();
        System.out.println("Done");
        ComptesDAO comptesDAO =new ComptesDAO();
        comptesDAO.insertCompte(compt);
        System.out.println("done");
         fr_acceuil con = new fr_acceuil();
        con.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_okActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showOpenDialog(null);
        File file = jFileChooser.getSelectedFile();
        ImageIcon imageIcon = new ImageIcon(file.getAbsolutePath());
        hostDir+=file.getName();
        imagename=file.getName();
        this.imgupload=file.getAbsolutePath();
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(129, 129,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        j_image.setText("");
        j_image.setIcon(new ImageIcon(newimg));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insecrition_client_presat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insecrition_client_presat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insecrition_client_presat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insecrition_client_presat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insecrition_client_presat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane Alert_quit;
    private javax.swing.JButton bt_ok;
    private javax.swing.JComboBox combo_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel j_image;
    private javax.swing.JLabel lbltype;
    private javax.swing.JPanel p_liste;
    private javax.swing.JPasswordField pf_pwd;
    private javax.swing.JTextField tf_adresse;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_nom;
    private javax.swing.JTextField tf_prenom;
    private javax.swing.JTextField tf_pseudo;
    private javax.swing.JTextField tf_tel;
    // End of variables declaration//GEN-END:variables
}
