/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GoldenCage.gui;

import de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel;
import goldencage.dao.PersonneDAO;
import goldencage.entities.Personne;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.coobird.thumbnailator.Thumbnails;
import goldencage.dao.OffresDAO;
import goldencage.entities.Offres;
import java.awt.Image;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author FGH
 */
public class jfr_compteClient extends javax.swing.JFrame {

    String filename = null;
    byte[] person_name = null;
    /**
     * Creates new form jfr_compteClient
     */
    
    private void recupererInfo(){
        PersonneDAO pdao =new PersonneDAO();
        Personne p = pdao.afficherPersonneById(Integer.parseInt(jlb_idcompte.getText()));
        jtf_cin.setText(""+p.getCin());
        jtf_nom.setText(p.getNom());
        jtf_prenom.setText(p.getPrenom());
        jtf_adresse.setText(p.getAdresse());
        jtf_email.setText(p.getEmail());
        jtf_numTel.setText(""+p.getTelephone());
        jlb_nomUser.setText(p.getPrenom()+" "+p.getNom());
        byte[] image =p.getPhoto();
//        ImageIcon format = null ;
//        try {
//            BufferedImage bf = ImageIO.read(new ByteArrayInputStream(image));
////            format= new ImageIcon(bf);
////            jlb_photoAdmin.setIcon(new ImageIcon(bf));
////            lb_photo.setIcon(format);
////        } catch (IOException ex) {
////            Logger.getLogger(jfr_compteAdmin.class.getName()).log(Level.SEVERE, null, ex);
////        }
//    }
//    
//    public void setIdCompte(int idCompte) {
//       //jlb_idcompte.setText(""+idCompte);
    }
    public jfr_compteClient() {
        initComponents();
        recupererInfo();
        jlb_idcompte.setVisible(false);
        jp_compte.setVisible(false);
        jp_reclamation.setVisible(false);
        jp_Services.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfChooser = new javax.swing.JFileChooser();
        jp_client = new javax.swing.JPanel();
        jlb_photoAdmin = new javax.swing.JLabel();
        jb_monCompte = new javax.swing.JButton();
        jb_deconnexion = new javax.swing.JButton();
        jlb_bonjour = new javax.swing.JLabel();
        jlb_nomUser = new javax.swing.JLabel();
        jlb_idcompte = new javax.swing.JLabel();
        jp_bouton = new javax.swing.JPanel();
        jb_acceuil = new javax.swing.JButton();
        jb_Services = new javax.swing.JButton();
        jb_offre = new javax.swing.JButton();
        jb_reclamation = new javax.swing.JButton();
        jb_taches = new javax.swing.JButton();
        jp_acceuil = new javax.swing.JPanel();
        jp_compte = new javax.swing.JPanel();
        lb_photo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jb_modifInfo = new javax.swing.JButton();
        jb_modifPWD = new javax.swing.JButton();
        jlb_nom = new javax.swing.JLabel();
        jlb_prenom = new javax.swing.JLabel();
        jlb_adresse = new javax.swing.JLabel();
        jlb_numTel = new javax.swing.JLabel();
        jlb_email = new javax.swing.JLabel();
        jtf_nom = new javax.swing.JTextField();
        jtf_prenom = new javax.swing.JTextField();
        jtf_adresse = new javax.swing.JTextField();
        jtf_email = new javax.swing.JTextField();
        jtf_numTel = new javax.swing.JTextField();
        jlb_pseudo = new javax.swing.JLabel();
        jtf_cin = new javax.swing.JTextField();
        jb_annulModif = new javax.swing.JButton();
        jb_saveModif = new javax.swing.JButton();
        jb_getphoto = new javax.swing.JButton();
        jtf_mdp = new javax.swing.JPasswordField();
        jtf_new_mdp1 = new javax.swing.JPasswordField();
        jtf_new_mdp2 = new javax.swing.JPasswordField();
        jp_Services = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_salle_fete = new javax.swing.JButton();
        btn_photographe = new javax.swing.JButton();
        btn_patisserie = new javax.swing.JButton();
        btn_robe_costume = new javax.swing.JButton();
        jp_salle_fete = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableoffre = new javax.swing.JTable();
        jp_photographe = new javax.swing.JPanel();
        lb_offre9 = new javax.swing.JLabel();
        lb_offre10 = new javax.swing.JLabel();
        lb_offre11 = new javax.swing.JLabel();
        lb_offre12 = new javax.swing.JLabel();
        lb_offre13 = new javax.swing.JLabel();
        lb_offre14 = new javax.swing.JLabel();
        lb_offre15 = new javax.swing.JLabel();
        lb_offre16 = new javax.swing.JLabel();
        jp_reclamation = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        lb_titreReclamation = new javax.swing.JLabel();
        jtf_emailReclamation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtf_textReclamation = new javax.swing.JTextArea();
        jtf_sujetReclamation = new javax.swing.JTextField();
        jb_EnvoyerReclamation = new javax.swing.JButton();
        jb_AnnulerReclamation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setResizable(false);

        jp_client.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jp_client.setLayout(null);

        jlb_photoAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_photoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/images/jlb_photoAdmin.png"))); // NOI18N
        jp_client.add(jlb_photoAdmin);
        jlb_photoAdmin.setBounds(12, 13, 76, 80);

        jb_monCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/V Card.png"))); // NOI18N
        jb_monCompte.setText("  Mon Compte    ");
        jb_monCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_monCompteActionPerformed(evt);
            }
        });
        jp_client.add(jb_monCompte);
        jb_monCompte.setBounds(835, 10, 140, 33);

        jb_deconnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Power.png"))); // NOI18N
        jb_deconnexion.setText("  Déconnexion    ");
        jb_deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_deconnexionActionPerformed(evt);
            }
        });
        jp_client.add(jb_deconnexion);
        jb_deconnexion.setBounds(835, 63, 140, 30);

        jlb_bonjour.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlb_bonjour.setForeground(new java.awt.Color(0, 0, 153));
        jlb_bonjour.setText("Bonjour,");
        jp_client.add(jlb_bonjour);
        jlb_bonjour.setBounds(100, 10, 71, 40);

        jlb_nomUser.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlb_nomUser.setForeground(new java.awt.Color(0, 0, 153));
        jlb_nomUser.setText("Nom d’utilisateur");
        jp_client.add(jlb_nomUser);
        jlb_nomUser.setBounds(100, 50, 170, 40);

        jlb_idcompte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlb_idcompte.setText("2");
        jp_client.add(jlb_idcompte);
        jlb_idcompte.setBounds(180, 20, 40, 30);

        jp_bouton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jb_acceuil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Home.png"))); // NOI18N
        jb_acceuil.setText("      Acceuil           ");
        jb_acceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_acceuilActionPerformed(evt);
            }
        });

        jb_Services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Books.png"))); // NOI18N
        jb_Services.setText("  Accéder aux services");
        jb_Services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ServicesActionPerformed(evt);
            }
        });

        jb_offre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Calendar.png"))); // NOI18N
        jb_offre.setText("  Mes offres Réservées");
        jb_offre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_offreActionPerformed(evt);
            }
        });

        jb_reclamation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Comments.png"))); // NOI18N
        jb_reclamation.setText(" Faire une Réclamation");
        jb_reclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_reclamationActionPerformed(evt);
            }
        });

        jb_taches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Table.png"))); // NOI18N
        jb_taches.setText("    Mes taches à faire  ");
        jb_taches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_tachesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_boutonLayout = new javax.swing.GroupLayout(jp_bouton);
        jp_bouton.setLayout(jp_boutonLayout);
        jp_boutonLayout.setHorizontalGroup(
            jp_boutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_boutonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_boutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_acceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_Services, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_offre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_reclamation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_taches, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_boutonLayout.setVerticalGroup(
            jp_boutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_boutonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_acceuil)
                .addGap(18, 18, 18)
                .addComponent(jb_Services)
                .addGap(18, 18, 18)
                .addComponent(jb_reclamation)
                .addGap(18, 18, 18)
                .addComponent(jb_offre)
                .addGap(18, 18, 18)
                .addComponent(jb_taches)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_acceuil.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jp_compte.setLayout(null);

        lb_photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_photo.setText("Photo");
        lb_photo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jp_compte.add(lb_photo);
        lb_photo.setBounds(590, 80, 130, 100);
        jp_compte.add(jSeparator1);
        jSeparator1.setBounds(10, 56, 510, 10);

        jb_modifInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Pencil.png"))); // NOI18N
        jb_modifInfo.setText("  Modifier mes informations");
        jb_modifInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modifInfoActionPerformed(evt);
            }
        });
        jp_compte.add(jb_modifInfo);
        jb_modifInfo.setBounds(10, 20, 190, 30);

        jb_modifPWD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Protect Blue.png"))); // NOI18N
        jb_modifPWD.setText("Modifier mon mot de passe");
        jb_modifPWD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modifPWDActionPerformed(evt);
            }
        });
        jp_compte.add(jb_modifPWD);
        jb_modifPWD.setBounds(210, 20, 200, 30);

        jlb_nom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_nom.setForeground(new java.awt.Color(0, 0, 153));
        jlb_nom.setText("Nom : ");
        jp_compte.add(jlb_nom);
        jlb_nom.setBounds(30, 120, 263, 30);

        jlb_prenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_prenom.setForeground(new java.awt.Color(0, 0, 153));
        jlb_prenom.setText("Prénom : ");
        jp_compte.add(jlb_prenom);
        jlb_prenom.setBounds(30, 160, 263, 30);

        jlb_adresse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_adresse.setForeground(new java.awt.Color(0, 0, 153));
        jlb_adresse.setText("Adresse :");
        jp_compte.add(jlb_adresse);
        jlb_adresse.setBounds(30, 200, 263, 30);

        jlb_numTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_numTel.setForeground(new java.awt.Color(0, 0, 153));
        jlb_numTel.setText("N° de télèphone :");
        jp_compte.add(jlb_numTel);
        jlb_numTel.setBounds(30, 280, 263, 30);

        jlb_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_email.setForeground(new java.awt.Color(0, 0, 153));
        jlb_email.setText("E-mail :");
        jp_compte.add(jlb_email);
        jlb_email.setBounds(30, 240, 263, 30);

        jtf_nom.setEnabled(false);
        jp_compte.add(jtf_nom);
        jtf_nom.setBounds(300, 120, 177, 30);

        jtf_prenom.setEnabled(false);
        jp_compte.add(jtf_prenom);
        jtf_prenom.setBounds(300, 160, 177, 30);

        jtf_adresse.setEnabled(false);
        jp_compte.add(jtf_adresse);
        jtf_adresse.setBounds(300, 200, 177, 30);

        jtf_email.setEnabled(false);
        jp_compte.add(jtf_email);
        jtf_email.setBounds(300, 240, 177, 30);

        jtf_numTel.setEnabled(false);
        jp_compte.add(jtf_numTel);
        jtf_numTel.setBounds(300, 280, 177, 30);

        jlb_pseudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlb_pseudo.setForeground(new java.awt.Color(0, 0, 153));
        jlb_pseudo.setText("CIN :");
        jp_compte.add(jlb_pseudo);
        jlb_pseudo.setBounds(30, 80, 263, 30);

        jtf_cin.setEnabled(false);
        jp_compte.add(jtf_cin);
        jtf_cin.setBounds(300, 80, 177, 30);

        jb_annulModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Reload.png"))); // NOI18N
        jb_annulModif.setText("Annuler");
        jb_annulModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_annulModifActionPerformed(evt);
            }
        });
        jp_compte.add(jb_annulModif);
        jb_annulModif.setBounds(500, 403, 113, 30);

        jb_saveModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Save.png"))); // NOI18N
        jb_saveModif.setText("Enregistrer");
        jb_saveModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_saveModifActionPerformed(evt);
            }
        });
        jp_compte.add(jb_saveModif);
        jb_saveModif.setBounds(380, 403, 113, 30);

        jb_getphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Image.png"))); // NOI18N
        jb_getphoto.setText("   Modifier ma photo");
        jb_getphoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_getphotoActionPerformed(evt);
            }
        });
        jp_compte.add(jb_getphoto);
        jb_getphoto.setBounds(560, 30, 180, 33);
        jp_compte.add(jtf_mdp);
        jtf_mdp.setBounds(300, 120, 180, 30);
        jp_compte.add(jtf_new_mdp1);
        jtf_new_mdp1.setBounds(300, 160, 180, 30);
        jp_compte.add(jtf_new_mdp2);
        jtf_new_mdp2.setBounds(300, 200, 180, 30);

        jp_Services.setLayout(null);
        jp_Services.add(jSeparator3);
        jSeparator3.setBounds(10, 61, 740, 10);

        btn_salle_fete.setText("Les salles de fête");
        btn_salle_fete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salle_feteActionPerformed(evt);
            }
        });
        jp_Services.add(btn_salle_fete);
        btn_salle_fete.setBounds(20, 23, 130, 30);

        btn_photographe.setText("Les photographes");
        btn_photographe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_photographeActionPerformed(evt);
            }
        });
        jp_Services.add(btn_photographe);
        btn_photographe.setBounds(160, 23, 130, 30);

        btn_patisserie.setText("Les patisseries");
        jp_Services.add(btn_patisserie);
        btn_patisserie.setBounds(300, 23, 120, 30);

        btn_robe_costume.setText("Les robes et les costumes");
        jp_Services.add(btn_robe_costume);
        btn_robe_costume.setBounds(430, 23, 190, 30);

        jTableoffre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableoffre);

        javax.swing.GroupLayout jp_salle_feteLayout = new javax.swing.GroupLayout(jp_salle_fete);
        jp_salle_fete.setLayout(jp_salle_feteLayout);
        jp_salle_feteLayout.setHorizontalGroup(
            jp_salle_feteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_salle_feteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(416, Short.MAX_VALUE))
        );
        jp_salle_feteLayout.setVerticalGroup(
            jp_salle_feteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_salle_feteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jp_Services.add(jp_salle_fete);
        jp_salle_fete.setBounds(10, 80, 730, 350);

        lb_offre9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/images/p1.jpg"))); // NOI18N

        lb_offre10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/images/p2.jpg"))); // NOI18N

        lb_offre11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/images/p3.jpg"))); // NOI18N

        lb_offre12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/images/p4.jpg"))); // NOI18N

        lb_offre13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/images/p5.jpg"))); // NOI18N

        lb_offre14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/images/p6.jpg"))); // NOI18N

        javax.swing.GroupLayout jp_photographeLayout = new javax.swing.GroupLayout(jp_photographe);
        jp_photographe.setLayout(jp_photographeLayout);
        jp_photographeLayout.setHorizontalGroup(
            jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_photographeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_photographeLayout.createSequentialGroup()
                        .addComponent(lb_offre9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_offre10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_offre11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_offre12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_photographeLayout.createSequentialGroup()
                        .addComponent(lb_offre13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_offre14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_offre15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_offre16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jp_photographeLayout.setVerticalGroup(
            jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_photographeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_offre11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_offre13, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre15, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jp_Services.add(jp_photographe);
        jp_photographe.setBounds(10, 80, 730, 350);

        lb_titreReclamation.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lb_titreReclamation.setForeground(new java.awt.Color(51, 51, 255));
        lb_titreReclamation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titreReclamation.setText("Deposer une réclamation");
        lb_titreReclamation.setBorder(new javax.swing.border.MatteBorder(null));

        jtf_emailReclamation.setForeground(new java.awt.Color(204, 204, 204));
        jtf_emailReclamation.setText("Tapper votre E-mail ici");

        jtf_textReclamation.setColumns(20);
        jtf_textReclamation.setForeground(new java.awt.Color(204, 204, 204));
        jtf_textReclamation.setLineWrap(true);
        jtf_textReclamation.setRows(5);
        jtf_textReclamation.setText("Tapper votre message ici ");
        jScrollPane1.setViewportView(jtf_textReclamation);

        jtf_sujetReclamation.setForeground(new java.awt.Color(204, 204, 204));
        jtf_sujetReclamation.setText("Sujet");

        jb_EnvoyerReclamation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Mail.png"))); // NOI18N
        jb_EnvoyerReclamation.setText("   Envoyer");
        jb_EnvoyerReclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EnvoyerReclamationActionPerformed(evt);
            }
        });

        jb_AnnulerReclamation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/goldencage/icons/Reload.png"))); // NOI18N
        jb_AnnulerReclamation.setText("   Annuler  ");
        jb_AnnulerReclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AnnulerReclamationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_reclamationLayout = new javax.swing.GroupLayout(jp_reclamation);
        jp_reclamation.setLayout(jp_reclamationLayout);
        jp_reclamationLayout.setHorizontalGroup(
            jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_reclamationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_reclamationLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_reclamationLayout.createSequentialGroup()
                        .addComponent(jb_EnvoyerReclamation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_AnnulerReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_reclamationLayout.createSequentialGroup()
                        .addGroup(jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_emailReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_sujetReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(150, 150, 150)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_reclamationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_titreReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jp_reclamationLayout.setVerticalGroup(
            jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_reclamationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titreReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_reclamationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_AnnulerReclamation)
                            .addComponent(jb_EnvoyerReclamation))
                        .addContainerGap())
                    .addGroup(jp_reclamationLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtf_emailReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_sujetReclamation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(75, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jp_acceuilLayout = new javax.swing.GroupLayout(jp_acceuil);
        jp_acceuil.setLayout(jp_acceuilLayout);
        jp_acceuilLayout.setHorizontalGroup(
            jp_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_acceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_compte, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jp_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_acceuilLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp_reclamation, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
            .addGroup(jp_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp_acceuilLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp_Services, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jp_acceuilLayout.setVerticalGroup(
            jp_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_acceuilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_compte, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jp_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_acceuilLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_reclamation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jp_acceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_acceuilLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp_Services, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_client, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jp_bouton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp_acceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_client, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_bouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_acceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1016, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_monCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_monCompteActionPerformed
        // TODO add your handling code here:
        recupererInfo();
        jp_compte.setVisible(true);
        jp_reclamation.setVisible(false);
        jp_Services.setVisible(false);

        jlb_nom.setText("Nom :");
        jlb_prenom.setText("Prénom :");
        jlb_adresse.setText("Adresse :");
        jlb_email.setVisible(true);
        jlb_numTel.setVisible(true);
        jlb_pseudo.setVisible(true);

        jtf_cin.setVisible(true);
        jtf_nom.setVisible(true);
        jtf_prenom.setVisible(true);
        jtf_adresse.setVisible(true);
        jtf_numTel.setVisible(true);
        jtf_email.setVisible(true);

        jtf_cin.setEnabled(false);
        jtf_nom.setEnabled(false);
        jtf_prenom.setEnabled(false);
        jtf_adresse.setEnabled(false);
        jtf_numTel.setEnabled(false);
        jtf_email.setEnabled(false);

        jb_annulModif.setVisible(false);
        jb_saveModif.setVisible(false);

        jtf_mdp.setVisible(false);
        jtf_new_mdp1.setVisible(false);
        jtf_new_mdp2.setVisible(false);

    }//GEN-LAST:event_jb_monCompteActionPerformed

    private void jb_deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_deconnexionActionPerformed
        // TODO add your handling code here:
        jfr_connexion jfr = new jfr_connexion();
        jfr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_deconnexionActionPerformed

    private void jb_acceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_acceuilActionPerformed
        // TODO add your handling code here:
        jp_compte.setVisible(false);
        jp_reclamation.setVisible(false);
        jp_Services.setVisible(false);
    }//GEN-LAST:event_jb_acceuilActionPerformed

    private void jb_ServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ServicesActionPerformed
        // TODO add your handling code here:
        jp_compte.setVisible(false);
        jp_reclamation.setVisible(false);
        jp_Services.setVisible(true);
        jp_photographe.setVisible(false);
        OffresDAO offresDAO=new OffresDAO();
        List<Offres> deals = offresDAO.afficherOffres();
        Object [][] data = new Object[deals.size()][3];
        String[] header =  new String [] {"Id", "Picture", "Name"};
        //recupereration donnees
        int i = 0;
        for(Offres d : deals){
            data[i][0]=d.getIdOffre();
            try{
                String url =d.getImage();// il ya un erreur car methode image not ready existe
                ImageIcon imageIcontable = new ImageIcon();
                // transform it 
                Image newimgtable = imageIcontable.getImage().getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
                data[i][1]= new ImageIcon(newimgtable);
            }catch (Exception e){
                
            }data[i][2]=d.getLibelle();
             i++;          }
        jTableoffre.setModel(new DefaultTableModel(data, new String[] { "ID",
				"Picture", "Name"}) {
			Class[] columnTypes = new Class[] { Integer.class, ImageIcon.class,
					String.class};
			public Class getColumnClass(int columnIndex) {
				return columnTypes[columnIndex];
			}
		});
        
        
    }//GEN-LAST:event_jb_ServicesActionPerformed

    private void jb_offreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_offreActionPerformed
        // TODO add your handling code here:
        jp_compte.setVisible(false);
        jp_reclamation.setVisible(false);
        jp_Services.setVisible(false);
    }//GEN-LAST:event_jb_offreActionPerformed

    private void jb_reclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_reclamationActionPerformed
        // TODO add your handling code here:
        jp_compte.setVisible(false);
        jp_reclamation.setVisible(true);
        jp_Services.setVisible(false);

       

    }//GEN-LAST:event_jb_reclamationActionPerformed

    private void jb_modifInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modifInfoActionPerformed
        // TODO add your handling code here:
        jlb_nom.setText("Nom :");
        jlb_prenom.setText("Prénom :");
        jlb_adresse.setText("Adresse :");
        jlb_email.setVisible(true);
        jlb_numTel.setVisible(true);
        jlb_pseudo.setVisible(true);

        jtf_nom.setVisible(true);
        jtf_prenom.setVisible(true);
        jtf_adresse.setVisible(true);
        jtf_numTel.setVisible(true);
        jtf_email.setVisible(true);
        jtf_cin.setVisible(true);

        jtf_cin.setEnabled(true);
        jtf_nom.setEnabled(true);
        jtf_prenom.setEnabled(true);
        jtf_adresse.setEnabled(true);
        jtf_numTel.setEnabled(true);
        jtf_email.setEnabled(true);

        jb_annulModif.setVisible(true);
        jb_saveModif.setVisible(true);

        jtf_mdp.setVisible(false);
        jtf_new_mdp1.setVisible(false);
        jtf_new_mdp2.setVisible(false);
    }//GEN-LAST:event_jb_modifInfoActionPerformed

    private void jb_modifPWDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modifPWDActionPerformed
        // TODO add your handling code here:
        jlb_nom.setText("Ancien mot de passe :");
        jlb_prenom.setText("Nouveau mot de passe :");
        jlb_adresse.setText("Confirmer le mot de passe :");
        jtf_mdp.setVisible(true);
        jtf_new_mdp1.setVisible(true);
        jtf_new_mdp2.setVisible(true);

        jtf_nom.setVisible(false);
        jtf_prenom.setVisible(false);
        jtf_adresse.setVisible(false);
        jlb_email.setVisible(false);
        jlb_numTel.setVisible(false);
        jlb_pseudo.setVisible(false);

        jtf_nom.setEnabled(false);
        jtf_prenom.setEnabled(false);
        jtf_adresse.setEnabled(false);
        jtf_numTel.setVisible(false);
        jtf_email.setVisible(false);
        jtf_cin.setVisible(false);

        jb_annulModif.setVisible(true);
        jb_saveModif.setVisible(true);
        jtf_mdp.setText("");
        jtf_new_mdp1.setText("");
        jtf_new_mdp2.setText("");
    }//GEN-LAST:event_jb_modifPWDActionPerformed

    private void jb_annulModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_annulModifActionPerformed
        // TODO add your handling code here:
        jb_annulModif.setVisible(false);
        jb_saveModif.setVisible(false);
        jtf_mdp.setText("");
        jtf_new_mdp1.setText("");
        jtf_new_mdp2.setText("");

        jtf_nom.setEnabled(false);
        jtf_prenom.setEnabled(false);
        jtf_adresse.setEnabled(false);
        jtf_numTel.setEnabled(false);
        jtf_email.setEnabled(false);
        jtf_cin.setEnabled(false);
        recupererInfo();
    }//GEN-LAST:event_jb_annulModifActionPerformed

    private void jb_saveModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_saveModifActionPerformed
        // TODO add your handling code here:
        jtf_nom.setEnabled(false);
        jtf_prenom.setEnabled(false);
        jtf_adresse.setEnabled(false);
        jtf_numTel.setEnabled(false);
        jtf_email.setEnabled(false);
        jtf_cin.setEnabled(false);
        jtf_mdp.setVisible(false);
        jtf_new_mdp1.setVisible(false);
        jtf_new_mdp2.setVisible(false);

        jb_annulModif.setVisible(false);
        jb_saveModif.setVisible(false);
        recupererInfo();
    }//GEN-LAST:event_jb_saveModifActionPerformed

    private void jb_getphotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_getphotoActionPerformed
        // TODO add your handling code here:
        FileFilter ff = new FileNameExtensionFilter("JPEG File", "jpg","jpeg");
        jfChooser.setFileFilter(ff);
        int n = jfChooser.showOpenDialog(this);
        if(n==jfChooser.APPROVE_OPTION)
        {
            String url = jfChooser.getSelectedFile().getAbsolutePath();
            File fr = jfChooser.getSelectedFile();
            //lb_photo.setIcon(new ImageIcon(""+fr));
            try {
                File image =new File(url);
                BufferedImage bf = ImageIO.read(image);
                BufferedImage thumb = Thumbnails.of(bf).size(160, 150).asBufferedImage();
                ByteArrayOutputStream os  = new ByteArrayOutputStream();
                ImageIO.write(thumb, "jpeg", os);

                InputStream is = new ByteArrayInputStream(os.toByteArray());

                FileInputStream fis =new FileInputStream(image);

                ByteArrayOutputStream bos  = new ByteArrayOutputStream();

                byte[] buff =new byte[1024];
                try {
                    for (int readnum ; (readnum = is.read(buff))!=-1; )
                    {
                        bos.write(buff,0,readnum);
                        //System.out.println("Read "+readnum+" bytes ," );
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }

                person_name = bos.toByteArray();

            } catch (Exception e) {
                e.printStackTrace();
            }
            lb_photo.setIcon(new ImageIcon(person_name));
            jlb_photoAdmin.setIcon(new ImageIcon(person_name));
        }

        System.out.println(person_name);
        PersonneDAO pdao = new PersonneDAO();
        Personne p = new Personne();
        p.setIdCompte(Integer.parseInt(jlb_idcompte.getText()));
        p.setPhoto(person_name);
        //pdao.deletePhotoPersonne(p.getIdCompte());
       // pdao.updatePhotoPersonne(p);
    }//GEN-LAST:event_jb_getphotoActionPerformed

    private void jb_EnvoyerReclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EnvoyerReclamationActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jb_EnvoyerReclamationActionPerformed

    private void jb_AnnulerReclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AnnulerReclamationActionPerformed
        // TODO add your handling code here:
        jtf_textReclamation.setText("");
    }//GEN-LAST:event_jb_AnnulerReclamationActionPerformed

    private void btn_salle_feteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salle_feteActionPerformed
//        // TODO add your handling code here:
//        jp_salle_fete.setVisible(true);
//        jp_photographe.setVisible(false);
    }//GEN-LAST:event_btn_salle_feteActionPerformed

    private void btn_photographeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_photographeActionPerformed
        // TODO add your handling code here:
//        jp_salle_fete.setVisible(false);
//        jp_photographe.setVisible(true);
    }//GEN-LAST:event_btn_photographeActionPerformed

    private void jb_tachesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_tachesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_tachesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                 //System.out.println(info.getName());
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    
                }*/
                UIManager.setLookAndFeel(new SyntheticaBlueIceLookAndFeel());
                

            }

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfr_connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(jfr_connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfr_compteClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_patisserie;
    private javax.swing.JButton btn_photographe;
    private javax.swing.JButton btn_robe_costume;
    private javax.swing.JButton btn_salle_fete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTableoffre;
    private javax.swing.JButton jb_AnnulerReclamation;
    private javax.swing.JButton jb_EnvoyerReclamation;
    private javax.swing.JButton jb_Services;
    private javax.swing.JButton jb_acceuil;
    private javax.swing.JButton jb_annulModif;
    private javax.swing.JButton jb_deconnexion;
    private javax.swing.JButton jb_getphoto;
    private javax.swing.JButton jb_modifInfo;
    private javax.swing.JButton jb_modifPWD;
    private javax.swing.JButton jb_monCompte;
    private javax.swing.JButton jb_offre;
    private javax.swing.JButton jb_reclamation;
    private javax.swing.JButton jb_saveModif;
    private javax.swing.JButton jb_taches;
    private javax.swing.JFileChooser jfChooser;
    private javax.swing.JLabel jlb_adresse;
    private javax.swing.JLabel jlb_bonjour;
    private javax.swing.JLabel jlb_email;
    private javax.swing.JLabel jlb_idcompte;
    private javax.swing.JLabel jlb_nom;
    private javax.swing.JLabel jlb_nomUser;
    private javax.swing.JLabel jlb_numTel;
    private javax.swing.JLabel jlb_photoAdmin;
    private javax.swing.JLabel jlb_prenom;
    private javax.swing.JLabel jlb_pseudo;
    private javax.swing.JPanel jp_Services;
    private javax.swing.JPanel jp_acceuil;
    private javax.swing.JPanel jp_bouton;
    private javax.swing.JPanel jp_client;
    private javax.swing.JPanel jp_compte;
    private javax.swing.JPanel jp_photographe;
    private javax.swing.JPanel jp_reclamation;
    private javax.swing.JPanel jp_salle_fete;
    private javax.swing.JTextField jtf_adresse;
    private javax.swing.JTextField jtf_cin;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_emailReclamation;
    private javax.swing.JPasswordField jtf_mdp;
    private javax.swing.JPasswordField jtf_new_mdp1;
    private javax.swing.JPasswordField jtf_new_mdp2;
    private javax.swing.JTextField jtf_nom;
    private javax.swing.JTextField jtf_numTel;
    private javax.swing.JTextField jtf_prenom;
    private javax.swing.JTextField jtf_sujetReclamation;
    private javax.swing.JTextArea jtf_textReclamation;
    private javax.swing.JLabel lb_offre10;
    private javax.swing.JLabel lb_offre11;
    private javax.swing.JLabel lb_offre12;
    private javax.swing.JLabel lb_offre13;
    private javax.swing.JLabel lb_offre14;
    private javax.swing.JLabel lb_offre15;
    private javax.swing.JLabel lb_offre16;
    private javax.swing.JLabel lb_offre9;
    private javax.swing.JLabel lb_photo;
    private javax.swing.JLabel lb_titreReclamation;
    // End of variables declaration//GEN-END:variables

   
}
