package GoldenCage.gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author FGH
 */
public class jfr_comptClient extends javax.swing.JFrame {

    /**
     * Creates new form jfr_comptClient
     */
    public jfr_comptClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alert_quit = new javax.swing.JOptionPane();
        alert_formulaireclient = new javax.swing.JOptionPane();
        p_bouton = new javax.swing.JPanel();
        bt_acceuil = new javax.swing.JButton();
        bt_reclamation = new javax.swing.JButton();
        bt_statistique = new javax.swing.JButton();
        bt_offre = new javax.swing.JButton();
        jp_client = new javax.swing.JPanel();
        lb_photo = new javax.swing.JLabel();
        lb_nom_client = new javax.swing.JLabel();
        bt_compte_client = new javax.swing.JButton();
        bt_deconnecter = new javax.swing.JButton();
        lb_nom_client1 = new javax.swing.JLabel();
        jp_acceuil = new javax.swing.JPanel();
        jp_reclamation = new javax.swing.JPanel();
        lb_titre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jp_service = new javax.swing.JPanel();
        btn_salle_fete = new javax.swing.JButton();
        btn_photographe = new javax.swing.JButton();
        btn_patisserie = new javax.swing.JButton();
        btn_robe_costume = new javax.swing.JButton();
        jp_photographe = new javax.swing.JPanel();
        lb_offre7 = new javax.swing.JLabel();
        lb_offre8 = new javax.swing.JLabel();
        lb_offre9 = new javax.swing.JLabel();
        lb_offre10 = new javax.swing.JLabel();
        lb_offre11 = new javax.swing.JLabel();
        lb_offre12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jp_salle_fete = new javax.swing.JPanel();
        lb_offre1 = new javax.swing.JLabel();
        lb_offre2 = new javax.swing.JLabel();
        lb_offre3 = new javax.swing.JLabel();
        lb_offre4 = new javax.swing.JLabel();
        lb_offre5 = new javax.swing.JLabel();
        lb_offre6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jp_compteclient = new javax.swing.JPanel();
        lb_prenom = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        lb_pseudo = new javax.swing.JLabel();
        lb_email = new javax.swing.JLabel();
        txt_pseudo = new javax.swing.JTextField();
        lb_adress = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        lb_tel = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_prenom = new javax.swing.JTextField();
        txt_adress = new javax.swing.JTextField();
        lb_nom = new javax.swing.JLabel();
        btn_modifier_comptclient = new javax.swing.JButton();
        btn_enregistrer = new javax.swing.JButton();
        btn_annuler = new javax.swing.JButton();
        lb_photo_golden = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        p_bouton.setBackground(new java.awt.Color(153, 204, 255));
        p_bouton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12), new java.awt.Color(135, 8, 165))); // NOI18N
        p_bouton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p_bouton.setLayout(null);

        bt_acceuil.setBackground(new java.awt.Color(204, 204, 255));
        bt_acceuil.setText("Acceuil");
        bt_acceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_acceuilActionPerformed(evt);
            }
        });
        p_bouton.add(bt_acceuil);
        bt_acceuil.setBounds(10, 70, 160, 23);

        bt_reclamation.setBackground(new java.awt.Color(204, 204, 255));
        bt_reclamation.setText("Faire une réclamation");
        bt_reclamation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reclamationActionPerformed(evt);
            }
        });
        p_bouton.add(bt_reclamation);
        bt_reclamation.setBounds(10, 160, 160, 23);

        bt_statistique.setBackground(new java.awt.Color(204, 204, 255));
        bt_statistique.setText("Mes offres réservées");
        bt_statistique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_statistiqueActionPerformed(evt);
            }
        });
        p_bouton.add(bt_statistique);
        bt_statistique.setBounds(10, 130, 160, 23);

        bt_offre.setBackground(new java.awt.Color(204, 204, 255));
        bt_offre.setText("Accéder au services");
        bt_offre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_offreActionPerformed(evt);
            }
        });
        p_bouton.add(bt_offre);
        bt_offre.setBounds(10, 100, 160, 23);

        jp_client.setBackground(new java.awt.Color(204, 204, 255));

        lb_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Client-2-icon.png"))); // NOI18N
        lb_photo.setText("Foto");

        lb_nom_client.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lb_nom_client.setText("Bonjour, ");

        bt_compte_client.setBackground(new java.awt.Color(153, 204, 255));
        bt_compte_client.setText("Mon Compte");
        bt_compte_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_compte_clientActionPerformed(evt);
            }
        });

        bt_deconnecter.setBackground(new java.awt.Color(153, 204, 255));
        bt_deconnecter.setText("Se déconnecter");
        bt_deconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deconnecterActionPerformed(evt);
            }
        });

        lb_nom_client1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lb_nom_client1.setText("Ben Salah Ali");

        javax.swing.GroupLayout jp_clientLayout = new javax.swing.GroupLayout(jp_client);
        jp_client.setLayout(jp_clientLayout);
        jp_clientLayout.setHorizontalGroup(
            jp_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_clientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_nom_client)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nom_client1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 390, Short.MAX_VALUE)
                .addGroup(jp_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_compte_client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_deconnecter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_clientLayout.setVerticalGroup(
            jp_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_clientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_clientLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jp_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_clientLayout.createSequentialGroup()
                                .addComponent(bt_compte_client)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_deconnecter))
                            .addGroup(jp_clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_nom_client, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_nom_client1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(jp_clientLayout.createSequentialGroup()
                        .addComponent(lb_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jp_acceuil.setBackground(new java.awt.Color(255, 255, 255));
        jp_acceuil.setLayout(null);

        lb_titre.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lb_titre.setForeground(new java.awt.Color(51, 51, 255));
        lb_titre.setText("Deposer une réclamation");

        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setRows(5);
        jTextArea1.setText("Tapper votre message ici ");
        jScrollPane1.setViewportView(jTextArea1);

        jButton5.setText("Annuler");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Envoyer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Tapper votre E-mail ici");

        javax.swing.GroupLayout jp_reclamationLayout = new javax.swing.GroupLayout(jp_reclamation);
        jp_reclamation.setLayout(jp_reclamationLayout);
        jp_reclamationLayout.setHorizontalGroup(
            jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_reclamationLayout.createSequentialGroup()
                .addGroup(jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_reclamationLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lb_titre))
                    .addGroup(jp_reclamationLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_reclamationLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jp_reclamationLayout.setVerticalGroup(
            jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_reclamationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jp_reclamationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jp_acceuil.add(jp_reclamation);
        jp_reclamation.setBounds(10, 10, 620, 380);

        jp_service.setLayout(null);

        btn_salle_fete.setText("Les salles de fête");
        btn_salle_fete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salle_feteActionPerformed(evt);
            }
        });
        jp_service.add(btn_salle_fete);
        btn_salle_fete.setBounds(10, 11, 130, 23);

        btn_photographe.setText("Les photographes");
        btn_photographe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_photographeActionPerformed(evt);
            }
        });
        jp_service.add(btn_photographe);
        btn_photographe.setBounds(150, 10, 130, 23);

        btn_patisserie.setText("Les patisseries");
        jp_service.add(btn_patisserie);
        btn_patisserie.setBounds(290, 10, 120, 23);

        btn_robe_costume.setText("Les robes et les costumes");
        jp_service.add(btn_robe_costume);
        btn_robe_costume.setBounds(420, 10, 190, 23);

        lb_offre7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p1.jpg"))); // NOI18N

        lb_offre8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p2.jpg"))); // NOI18N

        lb_offre9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p3.jpg"))); // NOI18N

        lb_offre10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p4.jpg"))); // NOI18N

        lb_offre11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p5.jpg"))); // NOI18N

        lb_offre12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/p6.jpg"))); // NOI18N

        jButton4.setText("Plus >>");

        javax.swing.GroupLayout jp_photographeLayout = new javax.swing.GroupLayout(jp_photographe);
        jp_photographe.setLayout(jp_photographeLayout);
        jp_photographeLayout.setHorizontalGroup(
            jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_photographeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jp_photographeLayout.createSequentialGroup()
                            .addComponent(lb_offre7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_offre8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_offre9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jp_photographeLayout.createSequentialGroup()
                            .addComponent(lb_offre10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_offre11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lb_offre12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jp_photographeLayout.setVerticalGroup(
            jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_photographeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_offre9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_photographeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_offre10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_offre12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_service.add(jp_photographe);
        jp_photographe.setBounds(10, 40, 600, 340);

        lb_offre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s1.jpg"))); // NOI18N

        lb_offre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s2.jpg"))); // NOI18N

        lb_offre3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s3.jpg"))); // NOI18N

        lb_offre4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s4.jpg"))); // NOI18N

        lb_offre5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s5.jpg"))); // NOI18N
        lb_offre5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_offre5MouseClicked(evt);
            }
        });

        lb_offre6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s6.jpg"))); // NOI18N

        jButton3.setText("Plus >>");

        javax.swing.GroupLayout jp_salle_feteLayout = new javax.swing.GroupLayout(jp_salle_fete);
        jp_salle_fete.setLayout(jp_salle_feteLayout);
        jp_salle_feteLayout.setHorizontalGroup(
            jp_salle_feteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_salle_feteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lb_offre1)
                .addGap(18, 18, 18)
                .addComponent(lb_offre2)
                .addGap(18, 18, 18)
                .addComponent(lb_offre3))
            .addGroup(jp_salle_feteLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lb_offre4)
                .addGap(18, 18, 18)
                .addComponent(lb_offre5)
                .addGap(18, 18, 18)
                .addComponent(lb_offre6))
            .addGroup(jp_salle_feteLayout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jButton3))
        );
        jp_salle_feteLayout.setVerticalGroup(
            jp_salle_feteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_salle_feteLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jp_salle_feteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_offre1)
                    .addComponent(lb_offre2)
                    .addComponent(lb_offre3))
                .addGap(18, 18, 18)
                .addGroup(jp_salle_feteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_offre4)
                    .addComponent(lb_offre5)
                    .addComponent(lb_offre6))
                .addGap(6, 6, 6)
                .addComponent(jButton3))
        );

        jp_service.add(jp_salle_fete);
        jp_salle_fete.setBounds(10, 39, 600, 330);

        jp_acceuil.add(jp_service);
        jp_service.setBounds(10, 11, 620, 380);

        jp_compteclient.setBackground(new java.awt.Color(255, 255, 255));
        jp_compteclient.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jp_compteclientPropertyChange(evt);
            }
        });

        lb_prenom.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lb_prenom.setText("Prenom : ");

        txt_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telKeyPressed(evt);
            }
        });

        lb_pseudo.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lb_pseudo.setText("Pseudo : ");

        lb_email.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lb_email.setText("E-mail : ");

        lb_adress.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lb_adress.setText("Adresse : ");

        txt_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomActionPerformed(evt);
            }
        });

        lb_tel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lb_tel.setText("Télèphone : ");

        lb_nom.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        lb_nom.setText("Nom : ");

        btn_modifier_comptclient.setBackground(new java.awt.Color(204, 204, 255));
        btn_modifier_comptclient.setText("Modifier");
        btn_modifier_comptclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_comptclientActionPerformed(evt);
            }
        });

        btn_enregistrer.setBackground(new java.awt.Color(204, 204, 255));
        btn_enregistrer.setText("Enregistrer");
        btn_enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enregistrerActionPerformed(evt);
            }
        });

        btn_annuler.setBackground(new java.awt.Color(204, 204, 255));
        btn_annuler.setText("Annuler");
        btn_annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_compteclientLayout = new javax.swing.GroupLayout(jp_compteclient);
        jp_compteclient.setLayout(jp_compteclientLayout);
        jp_compteclientLayout.setHorizontalGroup(
            jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_compteclientLayout.createSequentialGroup()
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_compteclientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_modifier_comptclient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_compteclientLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_enregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btn_annuler)
                .addContainerGap())
            .addGroup(jp_compteclientLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lb_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jp_compteclientLayout.setVerticalGroup(
            jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_compteclientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_modifier_comptclient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jp_compteclientLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_adress, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_adress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jp_compteclientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_annuler)
                    .addComponent(btn_enregistrer))
                .addContainerGap())
        );

        jp_acceuil.add(jp_compteclient);
        jp_compteclient.setBounds(10, 10, 550, 380);

        lb_photo_golden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/just_married_by_meago-d4v6nvr.png"))); // NOI18N
        jp_acceuil.add(lb_photo_golden);
        lb_photo_golden.setBounds(190, 56, 349, 274);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p_bouton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jp_acceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_bouton, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(jp_acceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(872, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_deconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deconnecterActionPerformed
        // TODO add your handling code here:
        jfr_inscription ins = new jfr_inscription();
        ins.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_deconnecterActionPerformed

    private void bt_statistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_statistiqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_statistiqueActionPerformed

    private void bt_compte_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_compte_clientActionPerformed
        // TODO add your handling code here:
        jp_service.setVisible(false);
        jp_compteclient.setVisible(true);
        lb_photo_golden.setVisible(false);
        jp_reclamation.setVisible(false);
        
        btn_enregistrer.setVisible(false);
        btn_modifier_comptclient.setEnabled(true);
        btn_annuler.setVisible(false);
        
        txt_nom.setEnabled(false);
        txt_prenom.setEnabled(false);
        txt_adress.setEnabled(false);
        txt_email.setEnabled(false);
        txt_tel.setEnabled(false);
        txt_pseudo.setEnabled(false);
        
        
    }//GEN-LAST:event_bt_compte_clientActionPerformed

    private void bt_acceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_acceuilActionPerformed
        // TODO add your handling code here:
        jp_service.setVisible(false);
        jp_compteclient.setVisible(false);
        lb_photo_golden.setVisible(true);
        jp_reclamation.setVisible(false);
    }//GEN-LAST:event_bt_acceuilActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lb_photo_golden.setVisible(true);
        jp_service.setVisible(false);
        jp_compteclient.setVisible(false);
        jp_reclamation.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void bt_offreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_offreActionPerformed
        // TODO add your handling code here:
        jp_service.setVisible(true);
        jp_photographe.setVisible(false);
        jp_salle_fete.setVisible(false);
        jp_reclamation.setVisible(false);
        
        jp_compteclient.setVisible(false);
        lb_photo_golden.setVisible(false);
    }//GEN-LAST:event_bt_offreActionPerformed

    private void txt_telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telKeyPressed
        // TODO add your handling code here:
        if (evt.getExtendedKeyCode()==8 )
        {

        }
        else if(evt.getKeyChar()> 58 || evt.getKeyChar()<47 )
        {
            alert_formulaireclient.showMessageDialog(this,"Veuillez entrer des numero svp!!", "Alert", WIDTH);
            txt_tel.setText(null);
        }
    }//GEN-LAST:event_txt_telKeyPressed

    private void txt_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomActionPerformed

    private void jp_compteclientPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jp_compteclientPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jp_compteclientPropertyChange

    private void btn_modifier_comptclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_comptclientActionPerformed
        // TODO add your handling code here:
        btn_enregistrer.setVisible(true);
        btn_annuler.setVisible(true);
        btn_modifier_comptclient.setEnabled(false);
        
        txt_nom.setEnabled(true);
        txt_prenom.setEnabled(true);
        txt_adress.setEnabled(true);
        txt_email.setEnabled(true);
        txt_tel.setEnabled(true);
        txt_pseudo.setEnabled(true);
    }//GEN-LAST:event_btn_modifier_comptclientActionPerformed

    private void btn_annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_annulerActionPerformed
        // TODO add your handling code here:
        btn_enregistrer.setVisible(false);
        btn_annuler.setVisible(false);
        btn_modifier_comptclient.setEnabled(true);
        
        txt_nom.setEnabled(false);
        txt_prenom.setEnabled(false);
        txt_adress.setEnabled(false);
        txt_email.setEnabled(false);
        txt_tel.setEnabled(false);
        txt_pseudo.setEnabled(false);
    }//GEN-LAST:event_btn_annulerActionPerformed

    private void btn_enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enregistrerActionPerformed
        // TODO add your handling code here:
        btn_enregistrer.setVisible(false);
        btn_annuler.setVisible(false);
        btn_modifier_comptclient.setEnabled(true);
        
        txt_nom.setEnabled(false);
        txt_prenom.setEnabled(false);
        txt_adress.setEnabled(false);
        txt_email.setEnabled(false);
        txt_tel.setEnabled(false);
        txt_pseudo.setEnabled(false);
    }//GEN-LAST:event_btn_enregistrerActionPerformed

    private void btn_salle_feteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salle_feteActionPerformed
        // TODO add your handling code here:
        jp_salle_fete.setVisible(true);
        jp_photographe.setVisible(false);
    }//GEN-LAST:event_btn_salle_feteActionPerformed

    private void btn_photographeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_photographeActionPerformed
        // TODO add your handling code here:
        jp_salle_fete.setVisible(false);
        jp_photographe.setVisible(true);
    }//GEN-LAST:event_btn_photographeActionPerformed

    private void lb_offre5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_offre5MouseClicked
        // TODO add your handling code here:
        jfr_evaluer_offre jfr = new jfr_evaluer_offre();
        jfr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lb_offre5MouseClicked

    private void bt_reclamationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reclamationActionPerformed
        // TODO add your handling code here:
        lb_photo_golden.setVisible(false);
        jp_service.setVisible(false);
        jp_compteclient.setVisible(false);
        jp_reclamation.setVisible(true);
    }//GEN-LAST:event_bt_reclamationActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        lb_photo_golden.setVisible(true);
        jp_service.setVisible(false);
        jp_compteclient.setVisible(false);
        jp_reclamation.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        lb_photo_golden.setVisible(true);
        jp_service.setVisible(false);
        jp_compteclient.setVisible(false);
        jp_reclamation.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfr_comptClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfr_comptClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfr_comptClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfr_comptClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfr_comptClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane Alert_quit;
    private javax.swing.JOptionPane alert_formulaireclient;
    private javax.swing.JButton bt_acceuil;
    private javax.swing.JButton bt_compte_client;
    private javax.swing.JButton bt_deconnecter;
    private javax.swing.JButton bt_offre;
    private javax.swing.JButton bt_reclamation;
    private javax.swing.JButton bt_statistique;
    private javax.swing.JButton btn_annuler;
    private javax.swing.JButton btn_enregistrer;
    private javax.swing.JButton btn_modifier_comptclient;
    private javax.swing.JButton btn_patisserie;
    private javax.swing.JButton btn_photographe;
    private javax.swing.JButton btn_robe_costume;
    private javax.swing.JButton btn_salle_fete;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jp_acceuil;
    private javax.swing.JPanel jp_client;
    private javax.swing.JPanel jp_compteclient;
    private javax.swing.JPanel jp_photographe;
    private javax.swing.JPanel jp_reclamation;
    private javax.swing.JPanel jp_salle_fete;
    private javax.swing.JPanel jp_service;
    private javax.swing.JLabel lb_adress;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_nom;
    private javax.swing.JLabel lb_nom_client;
    private javax.swing.JLabel lb_nom_client1;
    private javax.swing.JLabel lb_offre1;
    private javax.swing.JLabel lb_offre10;
    private javax.swing.JLabel lb_offre11;
    private javax.swing.JLabel lb_offre12;
    private javax.swing.JLabel lb_offre2;
    private javax.swing.JLabel lb_offre3;
    private javax.swing.JLabel lb_offre4;
    private javax.swing.JLabel lb_offre5;
    private javax.swing.JLabel lb_offre6;
    private javax.swing.JLabel lb_offre7;
    private javax.swing.JLabel lb_offre8;
    private javax.swing.JLabel lb_offre9;
    private javax.swing.JLabel lb_photo;
    private javax.swing.JLabel lb_photo_golden;
    private javax.swing.JLabel lb_prenom;
    private javax.swing.JLabel lb_pseudo;
    private javax.swing.JLabel lb_tel;
    private javax.swing.JLabel lb_titre;
    private javax.swing.JPanel p_bouton;
    private javax.swing.JTextField txt_adress;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txt_prenom;
    private javax.swing.JTextField txt_pseudo;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
