/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GoldenCage.gui;

import GoldenCage.Frame.PageAcceuil;

/**
 *
 * @author Amina
 */
public class Modifier_Admine extends javax.swing.JFrame {

    /**
     * Creates new form Ajouter_Admine
     */
    public Modifier_Admine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_bouton = new javax.swing.JPanel();
        bt_acceuil = new javax.swing.JButton();
        bt_compte_client = new javax.swing.JButton();
        bt_compte_prestataire = new javax.swing.JButton();
        bt_reclamation = new javax.swing.JButton();
        bt_statistique = new javax.swing.JButton();
        lb_nom_admin = new javax.swing.JLabel();
        lb_photo = new javax.swing.JLabel();
        bt_offre = new javax.swing.JButton();
        bt_comtpe_admin = new javax.swing.JButton();
        bt_quitter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tb = new javax.swing.JToolBar();
        tb_bt_ajouter = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        tb_bt_modifier = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        tb_bt_supprimer = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        tb_bt_lister = new javax.swing.JButton();
        table_admin = new javax.swing.JScrollPane();
        Table_Admin = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_bouton.setBackground(new java.awt.Color(233, 213, 230));
        p_bouton.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12), new java.awt.Color(135, 8, 165))); // NOI18N
        p_bouton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        p_bouton.setLayout(null);

        bt_acceuil.setText("Acceuil");
        bt_acceuil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_acceuilActionPerformed(evt);
            }
        });
        p_bouton.add(bt_acceuil);
        bt_acceuil.setBounds(10, 70, 140, 23);

        bt_compte_client.setText("Compte client");
        bt_compte_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_compte_clientActionPerformed(evt);
            }
        });
        p_bouton.add(bt_compte_client);
        bt_compte_client.setBounds(10, 130, 140, 23);

        bt_compte_prestataire.setText("Compte Prestataire");
        p_bouton.add(bt_compte_prestataire);
        bt_compte_prestataire.setBounds(10, 160, 140, 23);

        bt_reclamation.setText("Les réclamation");
        p_bouton.add(bt_reclamation);
        bt_reclamation.setBounds(10, 220, 140, 23);

        bt_statistique.setText("Les statistiques");
        bt_statistique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_statistiqueActionPerformed(evt);
            }
        });
        p_bouton.add(bt_statistique);
        bt_statistique.setBounds(10, 250, 140, 23);

        lb_nom_admin.setText("Administrateur");
        p_bouton.add(lb_nom_admin);
        lb_nom_admin.setBounds(60, 20, 100, 30);

        lb_photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GoldenCage/images/Client-2-icon.png"))); // NOI18N
        lb_photo.setText("Foto");
        p_bouton.add(lb_photo);
        lb_photo.setBounds(10, 4, 50, 60);

        bt_offre.setText("Les offres");
        p_bouton.add(bt_offre);
        bt_offre.setBounds(10, 190, 140, 23);

        bt_comtpe_admin.setText("Compte Admin");
        p_bouton.add(bt_comtpe_admin);
        bt_comtpe_admin.setBounds(10, 100, 140, 23);

        bt_quitter.setText("Quitter");
        bt_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quitterActionPerformed(evt);
            }
        });
        p_bouton.add(bt_quitter);
        bt_quitter.setBounds(10, 280, 140, 23);

        jPanel1.setBackground(new java.awt.Color(233, 213, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modifier Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 2, 12), new java.awt.Color(135, 8, 165))); // NOI18N

        tb.setBackground(new java.awt.Color(255, 204, 204));
        tb.setRollover(true);

        tb_bt_ajouter.setBackground(new java.awt.Color(255, 204, 204));
        tb_bt_ajouter.setText("Ajouter");
        tb_bt_ajouter.setFocusable(false);
        tb_bt_ajouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_bt_ajouter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_bt_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_bt_ajouterActionPerformed(evt);
            }
        });
        tb.add(tb_bt_ajouter);
        tb.add(jSeparator1);

        tb_bt_modifier.setBackground(new java.awt.Color(255, 204, 204));
        tb_bt_modifier.setText("Modifier");
        tb_bt_modifier.setFocusable(false);
        tb_bt_modifier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_bt_modifier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb.add(tb_bt_modifier);
        tb.add(jSeparator2);

        tb_bt_supprimer.setBackground(new java.awt.Color(255, 204, 204));
        tb_bt_supprimer.setText("Supprimer");
        tb_bt_supprimer.setFocusable(false);
        tb_bt_supprimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_bt_supprimer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb.add(tb_bt_supprimer);
        tb.add(jSeparator3);

        tb_bt_lister.setBackground(new java.awt.Color(255, 204, 204));
        tb_bt_lister.setText("Afficher tout");
        tb_bt_lister.setFocusable(false);
        tb_bt_lister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tb_bt_lister.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tb_bt_lister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_bt_listerActionPerformed(evt);
            }
        });
        tb.add(tb_bt_lister);

        Table_Admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°", "Nom", "Prenom", "Adresse", "E-mail", "Téléphone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_admin.setViewportView(Table_Admin);

        jButton1.setText("Enregistrer");

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(table_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2)))
                .addContainerGap(663, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_bouton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(p_bouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_acceuilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_acceuilActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_bt_acceuilActionPerformed

    private void bt_compte_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_compte_clientActionPerformed
        // TODO add your handling code here:
//        p_client.setVisible(true);
//        p_table.setVisible(true);
//        p_formulaire.setVisible(false);
        //        remplirclient();
    }//GEN-LAST:event_bt_compte_clientActionPerformed

    private void bt_statistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_statistiqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_statistiqueActionPerformed

    private void bt_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quitterActionPerformed
//        // TODO add your handling code here:
//        int n = Alert_quit.showConfirmDialog(this,"Quitter l'application ?","Quitter",Alert_quit.YES_NO_OPTION);
//        if (n == Alert_quit.YES_OPTION)
//        {
//            System.exit(0);
//        }
    }//GEN-LAST:event_bt_quitterActionPerformed

    private void tb_bt_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_bt_ajouterActionPerformed
        // TODO add your handling code here:
//        p_table.setVisible(false);
//        p_formulaire.setVisible(true);
    }//GEN-LAST:event_tb_bt_ajouterActionPerformed

    private void tb_bt_listerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_bt_listerActionPerformed
        // TODO add your handling code here:
       dispose();
       Afficher_Admine ii =new Afficher_Admine();
       ii.setVisible(true);
//        remplirclient();
    }//GEN-LAST:event_tb_bt_listerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 dispose();
       PageAcceuil jj=new PageAcceuil();
       jj.setVisible(true);      
       
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modifier_Admine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modifier_Admine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modifier_Admine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modifier_Admine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modifier_Admine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Admin;
    private javax.swing.JButton bt_acceuil;
    private javax.swing.JButton bt_compte_client;
    private javax.swing.JButton bt_compte_prestataire;
    private javax.swing.JButton bt_comtpe_admin;
    private javax.swing.JButton bt_offre;
    private javax.swing.JButton bt_quitter;
    private javax.swing.JButton bt_reclamation;
    private javax.swing.JButton bt_statistique;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JLabel lb_nom_admin;
    private javax.swing.JLabel lb_photo;
    private javax.swing.JPanel p_bouton;
    private javax.swing.JScrollPane table_admin;
    private javax.swing.JToolBar tb;
    private javax.swing.JButton tb_bt_ajouter;
    private javax.swing.JButton tb_bt_lister;
    private javax.swing.JButton tb_bt_modifier;
    private javax.swing.JButton tb_bt_supprimer;
    // End of variables declaration//GEN-END:variables
}
