/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GoldenCage.Frame;

/**
 *
 * @author FGH
 */
public class fr_connexion extends javax.swing.JFrame {

    /**
     * Creates new form fr_connexion
     */
    public fr_connexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alert_quit = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        lb_mdp = new javax.swing.JLabel();
        lb_login = new javax.swing.JLabel();
        txt_login = new javax.swing.JTextField();
        lb_photogoldencage = new javax.swing.JLabel();
        bt_connecter = new javax.swing.JButton();
        bt_quitter = new javax.swing.JButton();
        lb_glodencage = new javax.swing.JLabel();
        txt_mdp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Golden Cage");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(233, 213, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Connexion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(135, 8, 165))); // NOI18N
        jPanel1.setLayout(null);

        lb_mdp.setFont(new java.awt.Font("Aharoni", 3, 18)); // NOI18N
        lb_mdp.setForeground(new java.awt.Color(255, 255, 255));
        lb_mdp.setText("Mot de passe:");
        jPanel1.add(lb_mdp);
        lb_mdp.setBounds(270, 220, 117, 30);

        lb_login.setFont(new java.awt.Font("Aharoni", 3, 18)); // NOI18N
        lb_login.setForeground(new java.awt.Color(255, 255, 255));
        lb_login.setText("Login :");
        jPanel1.add(lb_login);
        lb_login.setBounds(270, 169, 78, 30);
        jPanel1.add(txt_login);
        txt_login.setBounds(400, 170, 131, 30);

        lb_photogoldencage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GoldenCage/images/1.png"))); // NOI18N
        jPanel1.add(lb_photogoldencage);
        lb_photogoldencage.setBounds(10, 130, 260, 240);

        bt_connecter.setBackground(new java.awt.Color(255, 153, 255));
        bt_connecter.setText("Se connecter");
        bt_connecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_connecterActionPerformed(evt);
            }
        });
        jPanel1.add(bt_connecter);
        bt_connecter.setBounds(330, 320, 110, 23);

        bt_quitter.setBackground(new java.awt.Color(255, 153, 255));
        bt_quitter.setText("Quitter");
        bt_quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_quitterActionPerformed(evt);
            }
        });
        jPanel1.add(bt_quitter);
        bt_quitter.setBounds(460, 320, 110, 23);

        lb_glodencage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GoldenCage/images/2.png"))); // NOI18N
        jPanel1.add(lb_glodencage);
        lb_glodencage.setBounds(280, 40, 260, 80);
        jPanel1.add(txt_mdp);
        txt_mdp.setBounds(400, 220, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(615, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_connecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_connecterActionPerformed
        
        fr_acceuil acc = new fr_acceuil();
        acc.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_bt_connecterActionPerformed

    private void bt_quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_quitterActionPerformed
        // TODO add your handling code here:
        int n = Alert_quit.showConfirmDialog(this,"Quitter l'application ?","Quitter",Alert_quit.YES_NO_OPTION);
     if (n == Alert_quit.YES_OPTION)
             {
                 System.exit(0);
             }
    }//GEN-LAST:event_bt_quitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_connexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JOptionPane Alert_quit;
    private javax.swing.JButton bt_connecter;
    private javax.swing.JButton bt_quitter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_glodencage;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_mdp;
    private javax.swing.JLabel lb_photogoldencage;
    private javax.swing.JTextField txt_login;
    private javax.swing.JPasswordField txt_mdp;
    // End of variables declaration//GEN-END:variables
}
